config/routes.rb
Rails.application.routes.draw do

  resources :portfolios
resources :cities
  resources :fruits
#  get 'pps/index'

#  get 'pps/show'

#  get 'pps/new'

#  get 'pps/edit'

#  get 'emps/new'

#  get 'emps/index'

#  get 'emps/show'

#  get 'emps/edit'

  #get 'users/new'

  #get 'users/show'

  #get 'users/index'

  #get 'users/edit'

 resources :pps

 resources :emps


  resources :users

  resources :details
  resources :blogs
  resources :students
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
extend FriendlyId
  friendly_id :title  , use: :slugged

end

app/models/city.rb
class City < ApplicationRecord
end

app/models/detail.rb
class Detail < ApplicationRecord

  extend FriendlyId
    friendly_id :title  , use: :slugged


end

app/models/portfolio.rb
class Portfolio < ApplicationRecord
end

app/models/pp.rb
class Pp < ApplicationRecord
end

app/models/student.rb
class Student < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord

  mount_uploader :image , UsersUploader

    paginates_per 25



end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: [:show, :edit, :update, :destroy]

  # GET /blogs
  # GET /blogs.json
  def index
    @blogs = Blog.all
  end

  # GET /blogs/1
  # GET /blogs/1.json
  def show
  end

  # GET /blogs/new
  def new
    @blog = Blog.new
  end

  # GET /blogs/1/edit
  def edit
  end

  # POST /blogs
  # POST /blogs.json
  def create
    @blog = Blog.new(blog_params)

    respond_to do |format|
      if @blog.save
        format.html { redirect_to @blog, notice: 'Blog was successfully created.' }
        format.json { render :show, status: :created, location: @blog }
      else
        format.html { render :new }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blogs/1
  # PATCH/PUT /blogs/1.json
  def update
    respond_to do |format|
      if @blog.update(blog_params)
        format.html { redirect_to @blog, notice: 'Blog was successfully updated.' }
        format.json { render :show, status: :ok, location: @blog }
      else
        format.html { render :edit }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blogs/1
  # DELETE /blogs/1.json
  def destroy
    @blog.destroy
    respond_to do |format|
      format.html { redirect_to blogs_url, notice: 'Blog was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blog
      @blog = Blog.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def blog_params
      params.require(:blog).permit(:title, :body)
    end
end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController


  def new

   @city = City.new

  end

  def create

        @city=City.new(city_params)

          if @city.save

            redirect_to action: :index

          else

            render action: :new

          end

  end


  def index

   @cities = City.all

  end

  def edit
  end

  def show
  end


   private

   def city_params

    params.require(:city).permit!

  end
end

app/controllers/emps_controller.rb
class EmpsController < ApplicationController
  def new
  end

  def index
  end

  def show
  end

  def edit
  end
end

app/controllers/pps_controller.rb
class PpsController < ApplicationController
  def index
  end

  def show
  end

  def new
  end

  def edit
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new

          @user =User.new

  end

  def create

    @user=User.new(user_params)

  #  binding.pry
  if @user.save

     flash[:notice]="user created successfully"

     redirect_to users_path

   else

     redirect_to new_user_path

   end


  end


  def edit

            #binding.pry
        @user =User.find(params[:id])

              #binding.pry
  end



def update

  @user =User.find(params[:id])



     if @user.update(user_params)

       flash[:notice]="user updated successfully"

       redirect_to user_path


     else

       redirect_to edit_user_path


     end

end


  def show

    @user = User.find(params[:id])

  end

# ned to pull dat from database and mapping data to views in that secnario we use methods or actions
# before creating a form we need to create a model.



 def index

@users= User.order(:name).page(params[:page])


end


def destroy

@user=User.find(params[:id])
  @user.destroy

end







  private


     def user_params


    params.require(:user).permit!

  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/details_helper.rb
module DetailsHelper
end

app/helpers/emps_helper.rb
module EmpsHelper
end

app/helpers/fruits_helper.rb
module FruitsHelper
end

app/helpers/portfolios_helper.rb
module PortfoliosHelper
end

app/helpers/pps_helper.rb
module PpsHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/blogs/_form.html.erb
<%= form_with(model: blog, local: true) do |form| %>
  <% if blog.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(blog.errors.count, "error") %> prohibited this blog from being saved:</h2>

      <ul>
      <% blog.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :blog_title %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body, id: :blog_body %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/blogs/edit.html.erb
<h1>Editing Blog</h1>

<%= render 'form', blog: @blog %>

<%= link_to 'Show', @blog %> |
<%= link_to 'Back', blogs_path %>

app/views/blogs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Blogs</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @blogs.each do |blog| %>
      <tr>
        <td><%= blog.title %></td>
        <td><%= blog.body %></td>
        <td><%= link_to 'Show', blog %></td>
        <td><%= link_to 'Edit', edit_blog_path(blog) %></td>
        <td><%= link_to 'Destroy', blog, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Blog', new_blog_path %>

app/views/blogs/new.html.erb
<h1>New Blog</h1>

<%= render 'form', blog: @blog %>

<%= link_to 'Back', blogs_path %>

app/views/blogs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @blog.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @blog.body %>
</p>

<%= link_to 'Edit', edit_blog_path(@blog) %> |
<%= link_to 'Back', blogs_path %>

app/views/cities/_city.html.erb
<td><%= city.name %></td>
<td><%= link_to 'Edit', edit_city_path(city) %></td>
<td><%= link_to 'Destroy', city, method: :delete, data: { confirm: 'Are you sure?' } %></td>
</tr>

app/views/cities/edit.html.erb
<h1>Cities#edit</h1>
<p>Find me in app/views/cities/edit.html.erb</p>

app/views/cities/index.html.erb
<div class="page-header">

<h2 class="text-center"> hi chakri vyas.  this is page header </h2>


</div>

<div class="container">

<div class="jumbotron">


<h2> namaskara bangalore  </h2>


</div>
</div>



<div class="well well-sm">Small Well</div>


kjvdjkvjdsbj


</div>








<p id="notice"><%= notice %></p>

<h1>Cities</h1>

<%= cache do %>

<table class="table table-dark">
  <thead>
    <tr>
      <th>CityNames</th>

    </tr>
  </thead>

  <tbody>
    <%= render  @cities %>
  </tbody>
</table>

<% end %>
<br>

<%= link_to 'New Detail', new_city_path %>

app/views/cities/new.html.erb
<%= form_for(@city) do |f| %>
<div class="container">
<div class="form-group">
<div class="label">

<%= f.label :name %>
<%= f.text_field :name , class:"form-control" %>

</div>
</div>
</div>

<div class="container">
<div class="form-group">
<div class="actions text-center">

<%= f.submit :submit  , class: " btn btn-primary"%>
</div>
</div>
</div>


<% end %>

<br />
<br />

<%= link_to 'index' , cities_path  , class: "btn btn-primary"%>

app/views/cities/show.html.erb
<h1>Cities#show</h1>
<p>Find me in app/views/cities/show.html.erb</p>

app/views/pps/edit.html.erb
<h1>Pps#edit</h1>
<p>Find me in app/views/pps/edit.html.erb</p>

app/views/pps/index.html.erb
<h1>Pps#index</h1>
<p>Find me in app/views/pps/index.html.erb</p>

app/views/pps/new.html.erb
<h1>Pps#new</h1>
<p>Find me in app/views/pps/new.html.erb</p>

app/views/pps/show.html.erb
<h1>Pps#show</h1>
<p>Find me in app/views/pps/show.html.erb</p>

app/views/users/_form.html.erb
 <div class="container">


<%= form_for(user) do |f| %>

<div class="container">
<div class="form-group">
<div class="field">
<%= f.label :name  %>
<%= f.text_field :name , class: "form-control"  %>
</div>
</div>
</div>



<div class="container">
<div class="form-group">
<div class="field">
<%= f.label :password  %>
<%= f.password_field :password , class: "form-control"  %>
</div>
</div>
</div>




<div class="container">
<div class="form-group">
<div class="field">
<%= f.label :confirmpassword  %>
<%= f.password_field :confirmpassword , class: "form-control"  %>
</div>
</div>
</div>








<div class="container">
<div class="form-group">
<div class="field">
<%=  f.label :mobilenumber %>
<%=  f.text_field :mobilenumber , class: "form-control" %>

</div>
</div>
</div>


<div class="container">
<div class="form-group">
<div class="field">
<%=  f.label :adhaarnumber %>
<%=  f.text_field :adhaarnumber , class: "form-control" %>

</div>
</div>
</div>


<div class="container">
<div class="form-group">
<div class="field">
<%=  f.label :pincode %>
<%=  f.text_field :pincode , class: "form-control" %>

</div>
</div>
</div>


<div class="container">
<div class="form-group">
<div class="field">
<%=  f.label :martialstatus %>
<%=  f.text_field :martialstatus , class: "form-control"%>

</div>
</div>
</div>



<div class="container">
<div class="form-group">
<div class="field">
<%=  f.label :languages %>
<%=  f.text_field :languages , class: "form-control"%>

</div>
</div>
</div>




<div class="container">
<div class="form-group">
<div class="field">
<%=  f.label :image %>
<%=  f.file_field :image %>

</div>
</div>
</div>









<div class="container">
<div class="form-group">
<div class="field">
<%=  f.submit :submit , class: "btn btn-primary btn-lg" %>

</div>
</div>
</div>
<% end %>

<%= link_to 'indexpage' , users_path , class: " btn btn-info" %>





</div>

app/views/users/edit.html.erb
<%= render 'form' , user: @user %>

app/views/users/index.html.erb
<div class="container">
<div class="table-responsive" %>
<table class="table table-striped">


<thead>
<tr>

  <td> Name</td>
  <td> Mobilenumber </td>
  <td> AdhaarNumber </td>
  <td> Pincode </td>
  <td>MartiaStatus </td>
  <td> Languages </td>
</thead>

<tbody>

 <% @users.each do |f| %>

<tr>
   <td><%= f.name %> </td>
   <td><%= f.mobilenumber %> </td>
   <td><%= f.adhaarnumber %> </td>
   <td><%= f.pincode %> </td>
   <td><%= f.martialstatus %></td>
   <td><%= f.languages %></td>
   <td><%= image_tag f.image , width: '50' %>
   <td><%= link_to 'show', user_path(f) %> </td>
   <td><%= link_to 'edit', edit_user_path(f) %></td>
   <td><%= link_to 'delete', f , method: :delete , data: {confirm: "Are you sure "} %> </td>

 </tr>

<% end %>


</tbody>
</table>

<%= link_to_next_page @users, 'Next Page' %>

<%= page_entries_info  @users %>

<br />

<%= link_to 'new' , new_user_path , class: "btn btn-info" %>

</div>
</div>


<div class="container">


<%= image_tag("chakri.jpg", width: 300) %>




</div>

app/views/users/new.html.erb
<%= render 'form',  user: @user %> 

app/views/users/show.html.erb
<div class="container">
<tr>
<td>Name: <%= @user.name %> </td>
<br />
<td>Mobilenumber: <%=@user.mobilenumber %></td>
<br/>
<td> Adhaarnumber: <%=@user.adhaarnumber %></td>
<br/>
<td>Pincode: <%=@user.pincode %></td>
<br/>
<td>Martialstatus: <%=@user.martialstatus %></td>
<br/>
<td>Languages: <%=@user.languages %></td>
<br/>
<td><%=image_tag @user.image , width: '100%' %></td>
<br/>


</tr>

</div>