config/routes.rb
Rails.application.routes.draw do

  resources :portfolios
resources :cities
  resources :fruits
#  get 'pps/index'

#  get 'pps/show'

#  get 'pps/new'

#  get 'pps/edit'

#  get 'emps/new'

#  get 'emps/index'

#  get 'emps/show'

#  get 'emps/edit'

  #get 'users/new'

  #get 'users/show'

  #get 'users/index'

  #get 'users/edit'

 resources :pps

 resources :emps


  resources :users

  resources :details
  resources :blogs
  resources :students
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
extend FriendlyId
  friendly_id :title  , use: :slugged

end

app/models/city.rb
class City < ApplicationRecord
end

app/models/detail.rb
class Detail < ApplicationRecord

  extend FriendlyId
    friendly_id :title  , use: :slugged


end

app/models/portfolio.rb
class Portfolio < ApplicationRecord
end

app/models/pp.rb
class Pp < ApplicationRecord
end

app/models/student.rb
class Student < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord

  mount_uploader :image , UsersUploader

    paginates_per 25



end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: [:show, :edit, :update, :destroy]

  # GET /blogs
  # GET /blogs.json
  def index
    @blogs = Blog.all
  end

  # GET /blogs/1
  # GET /blogs/1.json
  def show
  end

  # GET /blogs/new
  def new
    @blog = Blog.new
  end

  # GET /blogs/1/edit
  def edit
  end

  # POST /blogs
  # POST /blogs.json
  def create
    @blog = Blog.new(blog_params)

    respond_to do |format|
      if @blog.save
        format.html { redirect_to @blog, notice: 'Blog was successfully created.' }
        format.json { render :show, status: :created, location: @blog }
      else
        format.html { render :new }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blogs/1
  # PATCH/PUT /blogs/1.json
  def update
    respond_to do |format|
      if @blog.update(blog_params)
        format.html { redirect_to @blog, notice: 'Blog was successfully updated.' }
        format.json { render :show, status: :ok, location: @blog }
      else
        format.html { render :edit }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blogs/1
  # DELETE /blogs/1.json
  def destroy
    @blog.destroy
    respond_to do |format|
      format.html { redirect_to blogs_url, notice: 'Blog was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blog
      @blog = Blog.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def blog_params
      params.require(:blog).permit(:title, :body)
    end
end

app/controllers/details_controller.rb
class DetailsController < ApplicationController
  before_action :set_detail, only: [:show, :edit, :update, :destroy]

  # GET /details
  # GET /details.json
  def index
    @details = Detail.all
  end

  # GET /details/1
  # GET /details/1.json
  def show
  end

  # GET /details/new
  def new
    @detail = Detail.new
  end

  # GET /details/1/edit
  def edit
  end

  # POST /details
  # POST /details.json
  def create
    @detail = Detail.new(detail_params)

    respond_to do |format|
      if @detail.save
        format.html { redirect_to @detail, notice: 'Detail was successfully created.' }
        format.json { render :show, status: :created, location: @detail }
      else
        format.html { render :new }
        format.json { render json: @detail.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /details/1
  # PATCH/PUT /details/1.json
  def update
    respond_to do |format|
      if @detail.update(detail_params)
        format.html { redirect_to @detail, notice: 'Detail was successfully updated.' }
        format.json { render :show, status: :ok, location: @detail }
      else
        format.html { render :edit }
        format.json { render json: @detail.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /details/1
  # DELETE /details/1.json
  def destroy
    @detail.destroy
    respond_to do |format|
      format.html { redirect_to details_url, notice: 'Detail was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_detail
      @detail = Detail.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def detail_params
      params.require(:detail).permit(:title, :body)
    end
end

app/controllers/emps_controller.rb
class EmpsController < ApplicationController
  def new
  end

  def index
  end

  def show
  end

  def edit
  end
end

app/controllers/pps_controller.rb
class PpsController < ApplicationController
  def index
  end

  def show
  end

  def new
  end

  def edit
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new

          @user =User.new

  end

  def create

    @user=User.new(user_params)

  #  binding.pry
  if @user.save

     flash[:notice]="user created successfully"

     redirect_to users_path

   else

     redirect_to new_user_path

   end


  end


  def edit

            #binding.pry
        @user =User.find(params[:id])

              #binding.pry
  end



def update

  @user =User.find(params[:id])



     if @user.update(user_params)

       flash[:notice]="user updated successfully"

       redirect_to user_path


     else

       redirect_to edit_user_path


     end

end


  def show

    @user = User.find(params[:id])

  end

# ned to pull dat from database and mapping data to views in that secnario we use methods or actions
# before creating a form we need to create a model.



 def index

@users= User.order(:name).page(params[:page])


end


def destroy

@user=User.find(params[:id])
  @user.destroy

end







  private


     def user_params


    params.require(:user).permit!

  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/details_helper.rb
module DetailsHelper
end

app/helpers/emps_helper.rb
module EmpsHelper
end

app/helpers/fruits_helper.rb
module FruitsHelper
end

app/helpers/portfolios_helper.rb
module PortfoliosHelper
end

app/helpers/pps_helper.rb
module PpsHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/details/_form.html.erb
<%= form_with(model: detail, local: true) do |form| %>
  <% if detail.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(detail.errors.count, "error") %> prohibited this detail from being saved:</h2>

      <ul>
      <% detail.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


<div class="container">

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :detail_title , class: "form-control" %>
  </div>
<br />

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body, id: :detail_body , class: "form-control"%>
  </div>

<br />
  <div class="actions text-center">
    <%= form.submit :submit , class: "btn btn-primary " %>
  </div>
<% end %>

</div>

app/views/details/edit.html.erb
<h1>Editing Detail</h1>

<%= render 'form', detail: @detail %>

<%= link_to 'Show', @detail %> |
<%= link_to 'Back', details_path %>

app/views/details/index.html.erb
<div class="page-header">

<h2 class="text-center"> hi chakri vyas.  this is page header </h2>


</div>

<div class="container">

<div class="jumbotron">


<h2> namaskara bangalore  </h2>


</div>
</div>



<div class="well well-sm">Small Well</div>


kjvdjkvjdsbj


</div>









<p id="notice"><%= notice %></p>

<h1>Details</h1>

<table class="table table-dark">
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @details.each do |detail| %>
      <tr>
        <td><%= detail.title %></td>
        <td><%= detail.body %></td>
        <td><%= link_to 'Show', detail %></td>
        <td><%= link_to 'Edit', edit_detail_path(detail) %></td>
        <td><%= link_to 'Destroy', detail, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Detail', new_detail_path %>

<div class="well"> hi </div>

app/views/details/new.html.erb
<h1>New Detail</h1>

<%= render 'form', detail: @detail %>

<%= link_to 'Back', details_path %>

app/views/details/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @detail.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @detail.body %>
</p>

<%= link_to 'Edit', edit_detail_path(@detail) %> |
<%= link_to 'Back', details_path %>